<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KCVLOK6" failures="4" tests="24" name="CalculatorTestTestngSuite1" time="0.456" errors="0" timestamp="24 Mar 2022 17:51:08 GMT">
  <testcase classname="examplePackageForTestNg.CalculatorTest3" name="add0Test" time="0.029"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="add1Test" time="0.013"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest3" name="add2Test" time="0.008"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest" name="add1Test" time="0.039">
    <failure type="java.lang.AssertionError" message="expected [10] but found [111]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [111]
	at examplePackageForTestNg.CalculatorTest.add1Test(CalculatorTest.java:13)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- add1Test -->
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="add0TestDP" time="0.042"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="add0TestDP" time="0.01"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest" name="add3Test" time="0.082"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="add3Test" time="0.075"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="add2Test" time="0.017">
    <failure type="java.lang.AssertionError" message="expected [9] but found [11]">
      <![CDATA[java.lang.AssertionError: expected [9] but found [11]
	at examplePackageForTestNg.CalculatorTest2.add2Test(CalculatorTest2.java:21)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- add2Test -->
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="add0TestDP" time="0.036"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest" name="add2Test" time="0.017">
    <failure type="java.lang.AssertionError" message="expected [9] but found [11]">
      <![CDATA[java.lang.AssertionError: expected [9] but found [11]
	at examplePackageForTestNg.CalculatorTest.add2Test(CalculatorTest.java:18)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- add2Test -->
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="sub1Test" time="0.004"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="sub2Test" time="0.007"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest" name="sub1Test" time="0.038"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="mul1Test" time="0.004"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="add0TestDP" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [10] but found [11]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [11]
	at examplePackageForTestNg.CalculatorTest2.add0TestDP(CalculatorTest2.java:59)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- add0TestDP -->
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="add0TestDP" time="0.008"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest" name="mul1Test" time="0.077"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="devideByZeroTest" time="0.011"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest3" name="add1Test" time="0.21"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest" name="add4Test" time="0.002">
    <skipped/>
  </testcase> <!-- add4Test -->
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="add4Test" time="0.0">
    <skipped/>
  </testcase> <!-- add4Test -->
  <testcase classname="examplePackageForTestNg.CalculatorTest" name="devideByZeroTest" time="0.039"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest" name="sub2Test" time="0.149"/>
</testsuite> <!-- CalculatorTestTestngSuite1 -->
